ppw_story4_eyotawakanda/urls.py
from django.contrib import admin
from django.urls import path, include
from story4_eyotawakanda import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('')),
    path('story6/', include('story6_eyotawakanda.urls')),
    path('story4/', include('story4_eyotawakanda.urls')),
    path('story7/', include('story7_eyotawakanda.urls')),
    path('story8/', include('story8_eyotawakanda.urls')),
    path('', include('story9_eyotawakanda.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

story4_eyotawakanda/urls.py
from django.urls import path
from . import views

app_name = 'story4_eyotawakanda'

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('profile/', views.profile, name='profile'),
]

story6_eyotawakanda/urls.py
from django.urls import path
from . import views

app_name = 'story6_eyotawakanda'

urlpatterns = [
    path('', views.index, name="index"),
    path('tambah/', views.tambah, name="tambah"),
]

story7_eyotawakanda/urls.py
from django.urls import path
from . import views

app_name = 'story7_eyotawakanda'

urlpatterns = [
    path('', views.index, name="index"),
]

story8_eyotawakanda/urls.py
from django.urls import path
from . import views

app_name = 'story8_eyotawakanda'

urlpatterns = [
    path('', views.index, name="index"),
    path('request/', views.request, name="request")
]

story9_eyotawakanda/urls.py
from django.urls import path
from . import views

app_name = 'story9_eyotawakanda'

urlpatterns = [
    path('', views.index, name="index"),
]

story4_eyotawakanda/models.py
from django.db import models

# Create your models here.

story6_eyotawakanda/models.py
from django.db import models

class Aktivitas(models.Model):
    nama_aktivitas = models.CharField(max_length=100)
    def __str__(self):
        return self.nama_aktivitas

class Orang(models.Model):
    nama_orang = models.CharField(max_length=100)
    aktivitas = models.ForeignKey('Aktivitas', on_delete = models.CASCADE)
    def __str__(self):
        return self.nama_orang
# Create your models here.

story7_eyotawakanda/models.py
from django.db import models

# Create your models here.

story8_eyotawakanda/models.py
from django.db import models

# Create your models here.

story9_eyotawakanda/models.py
from django.db import models

# Create your models here.

story6_eyotawakanda/forms.py
from django.forms import ModelForm
from django.db.models import fields
from .models import Orang

class FormOrang(ModelForm):
    class Meta:
        model = Orang
        fields = ['nama_orang', 'aktivitas']

story9_eyotawakanda/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

story4_eyotawakanda/views.py
from django.shortcuts import render

# Create your views here.

def home (request):
    return render(request, "index.html")

def contact (request):
    return render(request, "contact-page.html")

def profile (request):
    return render(request, "profile.html")

story6_eyotawakanda/views.py
from django.shortcuts import render, redirect
from django.http import request
from .forms import FormOrang
from .models import Orang, Aktivitas

def index(request):
    orang = Orang.objects.all()
    aktivitas = Aktivitas.objects.all()
    context = {
        'orang':orang,
        'aktivitas':aktivitas,
        'judul':'Aktivitas'
    }
    return render(request, 'index6.html', context)

def tambah(request):
    form = FormOrang(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return redirect('story6_eyotawakanda:index')
    context = {
        'judul':'tambah',
        'form':form
    }
    return render(request, "tambah.html", context)
# Create your views here.

story7_eyotawakanda/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index7.html')
# Create your views here.

story8_eyotawakanda/views.py
from django.http import JsonResponse
from django.http import response
from django.shortcuts import render
import urllib3
import json


def index(request):
    return render(request, 'index8.html')

def request(request):
        searched = urllib3.PoolManager()
        response = searched.request('GET', "https://www.googleapis.com/books/v1/volumes?" +request.GET.urlencode())
        context = json.loads(response.data.decode('utf-8'))

        return JsonResponse(context)

# Create your views here.

story9_eyotawakanda/views.py
from django.http import response
from django.shortcuts import render, redirect
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm

def index(request):
    form = UserCreationForm()
    message = "Create your account"
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(username=form.cleaned_data.get("username"),
            password=form.cleaned_data.get("password1"))
            login(request, user)
    context = {'page_title': 'Login', 'form' : form}
    return render(request, 'index9.html', context)


# Create your views here.

story4_eyotawakanda/templates/base.html
{% load static %}
<html>
    <head>
        <link type="text/css" rel="stylesheet" href="{% static 'css/design.css' %}">
    </head>
    <body>
        <ul>
            <li><a href="{% url 'story4_eyotawakanda:home' %}">Home</a></li>
            <li><a href="{% url 'story4_eyotawakanda:contact' %}">Contact</a></li>
            <li><a href="{% url 'story4_eyotawakanda:profile' %}">Profile</a></li>
        </ul>
        {% block content %}

        {% endblock  %}
    </body>
</html>

story4_eyotawakanda/templates/contact-page.html
{% extends "base.html" %}
{% load static %}
{% block content %}
        <div class="con-head">
            <p class="head-text">
                CONTACTS:
            </p>
        </div>
        <div class="head-text-mini">
            <img id="contact" src="{% static 'img/line icon.png' %}" alt="">
            <p>menurutmuapalagi</p>
            <img id="contact" src="{% static 'img/phone icon.png' %}" alt="">
            <p>+62 812 9500 5479</p>
            <img id="contact" src="{% static 'img/email icon.png' %}" alt="">
            <p>eyota1318@gmail.com</p>
        </div>
{% endblock content %}

story4_eyotawakanda/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
        <div class="binder"></div>
        <div class="con-head">
            <table>
                <tr>
                    <td>
                        <div class="just-circle">
                            <div class="face-circle">
                                <img id="face" src="{% static 'img/FR17.jpg' %}" width=100% height=100% alt="">
                            </div>
                        </div>
                    </td>
                    <td></td>
                    <td>
                        <h1 class="head-text">
                            CURRICULUM VITAE
                        </h1>
                        <p class="head-text-mini">
                            CONTACTS
                        </p>
                    </td> 
                </tr>
            </table>
        </div>
        <br>
        <br>
        <br>
        <div class="con-1">
            <div class="con-2">
                <table>
                <tr><td><h1>ABOUT ME</h1></td></tr>
                <tr><td><p>Hello, my name is Eyota Wakanda, people always call me Waka. I am a 2nd year Information Systems Undergraduate Student at the University of Indonesia. My first year GPA is 3.61. I am a person that is eager to learn many things, including but not exclusive to: coding, literature history, music history, language and entertainment.</p></td></tr>
                <tr><td><br></td></tr>
                <tr><td><p>During my free time, my hobby is socializing with people, reading literature and enjoy various forms of entertainment.</p></td></tr>
                <tr><td><br></td></tr>
                <tr><td><p>In my major, I will be taking the technopreneurship minor because I am interested in starting a business at some point in the future. I have also done many research regarding the subject also as an effort to achieve that dream.</p></td></tr>
                <tr><td><br></td></tr>
                <tr><td><p>In a group project, I try to always do my part of the work ahead of schedule so I can help other group members if they have not finished their work. Besides that, I also like to mingle with many people to create social networks. Though my outgoing and extrovert personality is sometimes found to be overbearing for other people.</p></td></tr>
                <tr><td><br></td></tr>
                <tr><td><p>Despite preferring group projects over individual ones, I am also able to excel in individual projects if given enough time and motivation.</p></td></tr>
            </table>
        </div>
        </div>
        <br>
        <br>
        <br>
        <div class="con-1">
            <div class="con-2">
                <table>
                <tr>
                    <td>
                        <h1>EDUCATION BACKGROUND</h1>
                        <h3>University of Indonesia Computer Science Major Information Systems Undergraduate Student</h3>
                        <h4>(2019 - current)</h4>
                        <p>I have studied for two semesters as a Computer Science major learning various coding languages, mainly java and python for front end and back end development. As an Information Systems student, I have learned the basics of systems of information and also business and management.</p>
                        <h3>Regina Pacis Bogor High School</h3>
                        <h4>(2016 - 2019)</h4>
                        <p>During my High School period, I focused on natural sciences mostly because I enjoy trying to understand everything that happens in life. This has also allowed me to gain an increased knowledge about natural sciences that I have learned to apply on my day-to-day actions.</p>
                    </td>
                </tr>
                </table>
            </div>
        </div>
        <br>
        <br>
        <br>
        <div class="con-1">
            <div class="con-2">
                <table>
                <tr><td><h1>SKILLSETS & TOOLS</h1></td></tr>
                <tr><td>Analytical & Logical Thinking</td></tr>
                <tr><td>Problem Solving</td></tr>
                <tr><td>Creativity</td></tr>
                <tr><td>Communication</td></tr>
                <tr><td>Teamwork</td></tr>
                <tr><td>Visual Studio Code</td></tr>
                <tr><td>Microsoft Office</td></tr>
            </table>
            </div>
        </div>
        <br>
        <br>
        <br>
        <div class="con-1">
            <div class="con-2">
                <table>
                <tr>
                    <td>
                        <h1>ORGANIZATIONAL EXPERIENCE</h1>
                        <h3>SBF Akademis dan Kepemimpinan</h3>
                        <p>SBF or Sekolah BEM Fasilkom is an “event” held by the Faculty of Computer Science in the University of Indonesia that aims to give insight to the inner workings of the Academic and Leadership division of the “BEM”. I was the “Kepala pelaksana” of a talkshow held by other students “dibimbing” by Senior members of the division that talked about “mapres”</p>
                        <h3>Various Staff Positions in Events during High School</h3>
                        <p>My High School has held at least one art festivals every year and recruited members of the student body to work as staff members in the event. I have personally worked in the transportation and English Debate division in two separate events.</p>
                    </td>
                </tr>
            </table>
            </div>
        </div>
        <br>
        <br>
        <br>
        <div class="con-1">
            <div class="con-2">
                <table>
                <tr>
                    <td>
                        <h1>LANGUAGE PROFICIENCY</h1>
                        <h3>English</h3>
                        <h4>Professional Working Fluency</h4>
                        <p>I have 12 years of formal education on the subject, 6 of which is sponsored by LIA while in a partnership with my Junior and Senior High School. My mastery of the language have allowed me to use English fluently in both speaking and writing.                        </p>
                        <h3>Bahasa Indonesia</h3>
                        <h4>Native Fluency</h4>
                        <p>While living in a country that mainly speaks Indonesian for 18 years and receiving formal education on the language for at least 12 years, I have attained the ability to speak and write fluently in Indonesian.                        </p>
                    </td>
                </tr>
            </table>
            </div>
        </div>
{% endblock content %}

story4_eyotawakanda/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
        <table>
            <td>
                <tr>
                    <img src="https://cdn.discordapp.com/attachments/687132104097529893/687132198402392144/Untitled106.png" width="200" height="200" alt="">
                </tr>
            </td>
        </table>
        <table>
            <tr>
                <td>Nama</td>
                <td>Eyota Wakanda</td>
            </tr>
            <tr>
                <td>NPM</td>
                <td>1906353832</td>
            </tr>
            <tr>
                <td>Angkatan</td>
                <td>2019</td>
            </tr>
            <tr>
                <td>Tempat Kuliah</td>
                <td>Universitas Indonesia</td>
            </tr>
            <tr>
                <td>Hobi</td>
                <td>Bernafas, makan makanan gratis</td>
            </tr>
        </table>
        <table>
            <tr>
                <td>About me</td>
            </tr>
            <tr>
                <td>blablabla</td>
            </tr>
        </table>
        <table>
            <tr>
                <td>Contact info:</td>
            </tr>
            <tr>
                <td>http://line.me/ti/p/~menurutmuapalagi</td>
            </tr>
        </table>
{% endblock content %}

story6_eyotawakanda/templates/base6.html
{% load static %}
<html>

<head>
    <link type="text/css" rel="stylesheet" href="{% static 'css/design6.css' %}">
</head>

<body>
    <ul>
        <li><a href="{% url 'story6_eyotawakanda:index' %}">Home</a></li>
        <li><a href="{% url 'story6_eyotawakanda:tambah' %}">Tambah</a></li>
    </ul>
    {% block content %}

    {% endblock  %}
</body>

</html>

story6_eyotawakanda/templates/index6.html
{% extends "base6.html" %}
{% load static %}
{% block content %}
<h2>Aktivitas</h2>
<a class="button" href={% url 'story6_eyotawakanda:tambah' %}>Tambah Orang</a>
<div class="con-1">
    <div class=grid>
        {% for i in aktivitas %}
        <div class="table box">
            <div class="align-center">
                <h4>{{ i.nama_aktivitas }}</h4>
                <p>Orangnya siapa aja</p>
                {% for j in orang %}
                {% if j.aktivitas.nama_aktivitas == i.nama_aktivitas %}
                <p>{{ j.nama_orang }}</p>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content%}

story6_eyotawakanda/templates/tambah.html
{% extends "base6.html" %}
{% load static %}
{% block content %}
<h2>Tambah Orang</h2>
<div class="con-1">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="button button-1" type="submit" value="Submit" />    
    </form>
</div>
{% endblock content %}

story7_eyotawakanda/templates/base7.html
{% load static %}
<html>
    <head>
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
        <script src="{% static 'script.js' %}" defer></script>
        <link type="text/css" rel="stylesheet" href="{% static 'css/design7.css' %}">
    </head>
    <body>
        <ul>
        </ul>
        {% block content %}

        {% endblock  %}
    </body>
</html>

story7_eyotawakanda/templates/index7.html
{% extends "base7.html" %}
{% load static %}
{% block content %}
<h2>Accordion</h2>
<div class="con-1">
    <div class="baby-cordion">
        <div class="accor-title">
            <h5 class="dropdrown">
                <span class="title">Aktivitas saat ini</span>
                <span class="move-up">^</span>
                <span class="move-down">v</span>
            </h5>
        </div>
        <div class="accor-filling">
            <h6>Tidur</h6>
            <h6>Bermain Genshin Impact</h6>
            <h6>Belajar(?)</h6>
        </div>
    </div>
    <div class="baby-cordion">
        <div class="accor-title">
            <h5 class="dropdrown">
                <span class="title">Pengalaman organisasi/kepanitiaan</span>
                <span class="move-up">^</span>
                <span class="move-down">v</span>
            </h5>
        </div>
        <div class="accor-filling">
            <h6>Ketua pelaksana malam mapres ketika mengikuti SBF Akpem</h6>
        </div>
    </div>
    <div class="baby-cordion">
        <div class="accor-title">
            <h5 class="dropdrown">
                <span class="title">Prestasi</span>
                <span class="move-up">^</span>
                <span class="move-down">v</span>
            </h5>
        </div>
        <div class="accor-filling">
            <h6>Tidak ada ;-;</h6>
        </div>
    </div>
    <div class="baby-cordion">
        <div class="accor-title">
            <h5 class="dropdrown">
                <span class="title">Mimpi</span>
                <span class="move-up">^</span>
                <span class="move-down">v</span>
            </h5>
        </div>
        <div class="accor-filling">
            <h6>Tidak perlu memikirkan uang</h6>
        </div>
    </div>
</div>
{% endblock content%}

story8_eyotawakanda/templates/base8.html
{% load static %}
<html>
    <head>
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
        <script src="{% static 'script8.js' %}" defer></script>
        <link type="text/css" rel="stylesheet" href="{% static 'css/design8.css' %}">
    </head>
    <body>
        <ul>
        </ul>
        {% block content %}

        {% endblock  %}
    </body>
</html>

story8_eyotawakanda/templates/index8.html
{% extends "base8.html" %}
{% load static %}
{% block content %}
<h2>Searchbar</h2>
<div class="con-1">
    <div class="">
        <form id="search-form">
            <input type="text" id="search-input" />
            <input class="button" type="submit" value="Submit" />
        </form>
    </div>
</div>
<br>
<div class="con-1">
    <div id="result"></div>
</div>
{% endblock content%}

story9_eyotawakanda/templates/base9.html
{% load static %}
<html>
    <head>
        <link type="text/css" rel="stylesheet" href="{% static 'css/design9.css' %}">
    </head>
    <body>
        <ul>
        </ul>
        {% block content %}

        {% endblock  %}
    </body>
</html>

story9_eyotawakanda/templates/index9.html
{% extends 'base9.html' %}
{% load static %}
{% block content %}
<div>
    <div class="con-1">
    {% if user.is_authenticated %}
    <h1>Welcome back {{user.username}}</h1>
    <br>
    <p>Hi</p>
    <a class="button" href="{% url 'logout' %}">Logout</a>
    {% else %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button class="button">Submit</button>
    </form>

    <h3>Already have an account?</h3>
    <a class="button" href="{% url 'login' %}">Login</a>
    
    {% endif %}
    </div>
</div>
{% endblock content %}